#ifndef __DATA_H__
#define __DATA_H__

typedef enum 
{
    SUCCESS_CODE,
    ERR_IO,
    ERR_RANGE,
    ERR_MEM
} status_t;

typedef enum 
{
    EXIT_PROGRAM,
    CALC_ARITHMETIC_EXPRESSION_BY_ARRAY,
    ADD_STACK_ELEMENT_TO_ARRAY,
    DELETE_STACK_ELEMENT_FROM_ARRAY,
    PRINT_STACK_FROM_ARRAY,
    CALC_ARITHMETIC_EXPRESSION_BY_LIST,
    ADD_STACK_ELEMENT_TO_LIST,
    DELETE_STACK_ELEMENT_FROM_LIST,
    PRINT_STACK_FROM_LIST,
    COMPARE_PERFORMANCE,
    PRINT_ARRAY_OF_FREE_MEMORY_AREAS
} menu_option_t;

#endif