#ifndef __STATUS_H__
#define __STATUS_H__

typedef enum 
{
    SUCCCESS_CODE,
    INVALID_QUANTITY,
    INVALID_POINTER,
    INVALID_INPUT,
    MEM_ALLOCATE_ERROR,
    INVALID_CHOICE,
    FILE_OPEN_ERROR,
    FILE_READ_ERROR,
    ARR_PROCESSING_ERROR,
    RECORDS_ARR_OVERFLOWED,
    INVALID_DELETE
} status_t;

#endif