#ifndef DATA_H
#define DATA_H

#include "stdio.h"
#include <stdlib.h>

#define MENU_OPTIONS 17
#define MAX_FILENAME_LENGTH 50
#define MAX_PREFIX_SIZE 1000
#define TESTS_QUANTITY 1000
#define MAX_STRING_LENGTH 256

typedef enum
{
    OK_CODE,
    INPUT_ERR_CODE,
    INVALID_PTR_CODE,
    MEMORY_ERR_CODE,
    FILE_OPEN_ERR_CODE,
    FILE_READ_ERR_CODE,
    NOTHING_TO_DELETE_CODE,
    EMPTY_TREE_CODE,
    NOT_FOUND_CODE
} result_t;

typedef enum
{
    EXIT,
    MAKE_TREE_FROM_FILE,
    PRINT_BST_TREE,
    PRINT_AVL_TREE,
    SHOW_BST_TREE,
    SHOW_AVL_TREE,
    ADD_WORD_TO_TREE,
    DELETE_WORD_FROM_TREE,
    FIND_WORD_IN_TREE,
    MAKE_HASH_TABLE_FROM_FILE,
    PRINT_CHAINING_HASH_TABLE,
    PRINT_OPEN_HASH_TABLE,
    SHOW_CHAINING_HASH_TABLE,
    SHOW_OPEN_HASH_TABLE,
    ADD_WORD_TO_HASH_TABLE,
    DELETE_WORD_FROM_HASH_TABLE,
    FIND_WORD_IN_HASH_TABLE,
    COMPARE_EFFICIENCY
} menu_option_t;

#endif